USE ridenepal;

ALTER TABLE bulk_rent_requests
  ADD COLUMN IF NOT EXISTS vendor_id CHAR(36) NULL AFTER user_id,
  ADD COLUMN IF NOT EXISTS price_per_bike DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS total_amount DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS pickup_location VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS vendor_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS quoted_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS paid_at DATETIME NULL;