USE ridenepal;

ALTER TABLE gallery_posts CHANGE COLUMN image_url image_path TEXT NOT NULL;
ALTER TABLE gallery_posts ADD COLUMN IF NOT EXISTS place VARCHAR(120) NULL;

CREATE TABLE IF NOT EXISTS gallery_comments (
  id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  post_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES gallery_posts(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;