/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as VendorRegisterRouteImport } from './routes/vendor-register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BulkRentRouteImport } from './routes/bulk-rent'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BikeBikeIdRouteImport } from './routes/bike.$bikeId'
import { Route as ApiGalleryUploadRouteImport } from './routes/api/gallery-upload'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVendorDashboardRouteImport } from './routes/_authenticated/vendor-dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedTrackBookingIdRouteImport } from './routes/_authenticated/track.$bookingId'
import { Route as AuthenticatedExtendBookingIdRouteImport } from './routes/_authenticated/extend.$bookingId'
import { Route as AuthenticatedCheckoutBookingIdRouteImport } from './routes/_authenticated/checkout.$bookingId'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/_admin/vendors'
import { Route as AuthenticatedAdminTrackingRouteImport } from './routes/_authenticated/_admin/tracking'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/_admin/messages'
import { Route as AuthenticatedAdminManageBikesRouteImport } from './routes/_authenticated/_admin/manage-bikes'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/_admin/commissions'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminCustomerUserIdRouteImport } from './routes/_authenticated/_admin/customer.$userId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor-register',
  path: '/vendor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRentRoute = BulkRentRouteImport.update({
  id: '/bulk-rent',
  path: '/bulk-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikeBikeIdRoute = BikeBikeIdRouteImport.update({
  id: '/bike/$bikeId',
  path: '/bike/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryUploadRoute = ApiGalleryUploadRouteImport.update({
  id: '/api/gallery-upload',
  path: '/api/gallery-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorDashboardRoute =
  AuthenticatedVendorDashboardRouteImport.update({
    id: '/vendor-dashboard',
    path: '/vendor-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackBookingIdRoute =
  AuthenticatedTrackBookingIdRouteImport.update({
    id: '/track/$bookingId',
    path: '/track/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtendBookingIdRoute =
  AuthenticatedExtendBookingIdRouteImport.update({
    id: '/extend/$bookingId',
    path: '/extend/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutBookingIdRoute =
  AuthenticatedCheckoutBookingIdRouteImport.update({
    id: '/checkout/$bookingId',
    path: '/checkout/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTrackingRoute =
  AuthenticatedAdminTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminManageBikesRoute =
  AuthenticatedAdminManageBikesRouteImport.update({
    id: '/manage-bikes',
    path: '/manage-bikes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCustomerUserIdRoute =
  AuthenticatedAdminCustomerUserIdRouteImport.update({
    id: '/customer/$userId',
    path: '/customer/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/bulk-rent': typeof BulkRentRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment-return': typeof PaymentReturnRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/vendor-dashboard': typeof AuthenticatedVendorDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gallery-upload': typeof ApiGalleryUploadRoute
  '/bike/$bikeId': typeof BikeBikeIdRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/manage-bikes': typeof AuthenticatedAdminManageBikesRoute
  '/messages': typeof AuthenticatedAdminMessagesRoute
  '/tracking': typeof AuthenticatedAdminTrackingRoute
  '/vendors': typeof AuthenticatedAdminVendorsRoute
  '/checkout/$bookingId': typeof AuthenticatedCheckoutBookingIdRoute
  '/extend/$bookingId': typeof AuthenticatedExtendBookingIdRoute
  '/track/$bookingId': typeof AuthenticatedTrackBookingIdRoute
  '/customer/$userId': typeof AuthenticatedAdminCustomerUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/bulk-rent': typeof BulkRentRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment-return': typeof PaymentReturnRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/vendor-dashboard': typeof AuthenticatedVendorDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gallery-upload': typeof ApiGalleryUploadRoute
  '/bike/$bikeId': typeof BikeBikeIdRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/manage-bikes': typeof AuthenticatedAdminManageBikesRoute
  '/messages': typeof AuthenticatedAdminMessagesRoute
  '/tracking': typeof AuthenticatedAdminTrackingRoute
  '/vendors': typeof AuthenticatedAdminVendorsRoute
  '/checkout/$bookingId': typeof AuthenticatedCheckoutBookingIdRoute
  '/extend/$bookingId': typeof AuthenticatedExtendBookingIdRoute
  '/track/$bookingId': typeof AuthenticatedTrackBookingIdRoute
  '/customer/$userId': typeof AuthenticatedAdminCustomerUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/bulk-rent': typeof BulkRentRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment-return': typeof PaymentReturnRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor-register': typeof VendorRegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/vendor-dashboard': typeof AuthenticatedVendorDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gallery-upload': typeof ApiGalleryUploadRoute
  '/bike/$bikeId': typeof BikeBikeIdRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/_admin/manage-bikes': typeof AuthenticatedAdminManageBikesRoute
  '/_authenticated/_admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/_admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/_authenticated/_admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/checkout/$bookingId': typeof AuthenticatedCheckoutBookingIdRoute
  '/_authenticated/extend/$bookingId': typeof AuthenticatedExtendBookingIdRoute
  '/_authenticated/track/$bookingId': typeof AuthenticatedTrackBookingIdRoute
  '/_authenticated/_admin/customer/$userId': typeof AuthenticatedAdminCustomerUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/auth-callback'
    | '/bulk-rent'
    | '/chat'
    | '/community'
    | '/fleet'
    | '/gallery'
    | '/onboarding'
    | '/otp'
    | '/payment-return'
    | '/rewards'
    | '/sitemap.xml'
    | '/vendor-register'
    | '/verify-otp'
    | '/dashboard'
    | '/profile'
    | '/vendor-dashboard'
    | '/api/chat'
    | '/api/gallery-upload'
    | '/bike/$bikeId'
    | '/admin'
    | '/commissions'
    | '/manage-bikes'
    | '/messages'
    | '/tracking'
    | '/vendors'
    | '/checkout/$bookingId'
    | '/extend/$bookingId'
    | '/track/$bookingId'
    | '/customer/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/auth-callback'
    | '/bulk-rent'
    | '/chat'
    | '/community'
    | '/fleet'
    | '/gallery'
    | '/onboarding'
    | '/otp'
    | '/payment-return'
    | '/rewards'
    | '/sitemap.xml'
    | '/vendor-register'
    | '/verify-otp'
    | '/dashboard'
    | '/profile'
    | '/vendor-dashboard'
    | '/api/chat'
    | '/api/gallery-upload'
    | '/bike/$bikeId'
    | '/admin'
    | '/commissions'
    | '/manage-bikes'
    | '/messages'
    | '/tracking'
    | '/vendors'
    | '/checkout/$bookingId'
    | '/extend/$bookingId'
    | '/track/$bookingId'
    | '/customer/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/auth'
    | '/auth-callback'
    | '/bulk-rent'
    | '/chat'
    | '/community'
    | '/fleet'
    | '/gallery'
    | '/onboarding'
    | '/otp'
    | '/payment-return'
    | '/rewards'
    | '/sitemap.xml'
    | '/vendor-register'
    | '/verify-otp'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/vendor-dashboard'
    | '/api/chat'
    | '/api/gallery-upload'
    | '/bike/$bikeId'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/commissions'
    | '/_authenticated/_admin/manage-bikes'
    | '/_authenticated/_admin/messages'
    | '/_authenticated/_admin/tracking'
    | '/_authenticated/_admin/vendors'
    | '/_authenticated/checkout/$bookingId'
    | '/_authenticated/extend/$bookingId'
    | '/_authenticated/track/$bookingId'
    | '/_authenticated/_admin/customer/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BulkRentRoute: typeof BulkRentRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  FleetRoute: typeof FleetRoute
  GalleryRoute: typeof GalleryRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  RewardsRoute: typeof RewardsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGalleryUploadRoute: typeof ApiGalleryUploadRoute
  BikeBikeIdRoute: typeof BikeBikeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-register': {
      id: '/vendor-register'
      path: '/vendor-register'
      fullPath: '/vendor-register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-rent': {
      id: '/bulk-rent'
      path: '/bulk-rent'
      fullPath: '/bulk-rent'
      preLoaderRoute: typeof BulkRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike/$bikeId': {
      id: '/bike/$bikeId'
      path: '/bike/$bikeId'
      fullPath: '/bike/$bikeId'
      preLoaderRoute: typeof BikeBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery-upload': {
      id: '/api/gallery-upload'
      path: '/api/gallery-upload'
      fullPath: '/api/gallery-upload'
      preLoaderRoute: typeof ApiGalleryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor-dashboard': {
      id: '/_authenticated/vendor-dashboard'
      path: '/vendor-dashboard'
      fullPath: '/vendor-dashboard'
      preLoaderRoute: typeof AuthenticatedVendorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/track/$bookingId': {
      id: '/_authenticated/track/$bookingId'
      path: '/track/$bookingId'
      fullPath: '/track/$bookingId'
      preLoaderRoute: typeof AuthenticatedTrackBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extend/$bookingId': {
      id: '/_authenticated/extend/$bookingId'
      path: '/extend/$bookingId'
      fullPath: '/extend/$bookingId'
      preLoaderRoute: typeof AuthenticatedExtendBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$bookingId': {
      id: '/_authenticated/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/checkout/$bookingId'
      preLoaderRoute: typeof AuthenticatedCheckoutBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/vendors': {
      id: '/_authenticated/_admin/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/tracking': {
      id: '/_authenticated/_admin/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedAdminTrackingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/messages': {
      id: '/_authenticated/_admin/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/manage-bikes': {
      id: '/_authenticated/_admin/manage-bikes'
      path: '/manage-bikes'
      fullPath: '/manage-bikes'
      preLoaderRoute: typeof AuthenticatedAdminManageBikesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/commissions': {
      id: '/_authenticated/_admin/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/customer/$userId': {
      id: '/_authenticated/_admin/customer/$userId'
      path: '/customer/$userId'
      fullPath: '/customer/$userId'
      preLoaderRoute: typeof AuthenticatedAdminCustomerUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminManageBikesRoute: typeof AuthenticatedAdminManageBikesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminTrackingRoute: typeof AuthenticatedAdminTrackingRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminCustomerUserIdRoute: typeof AuthenticatedAdminCustomerUserIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
    AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
    AuthenticatedAdminManageBikesRoute: AuthenticatedAdminManageBikesRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminTrackingRoute: AuthenticatedAdminTrackingRoute,
    AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
    AuthenticatedAdminCustomerUserIdRoute:
      AuthenticatedAdminCustomerUserIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVendorDashboardRoute: typeof AuthenticatedVendorDashboardRoute
  AuthenticatedCheckoutBookingIdRoute: typeof AuthenticatedCheckoutBookingIdRoute
  AuthenticatedExtendBookingIdRoute: typeof AuthenticatedExtendBookingIdRoute
  AuthenticatedTrackBookingIdRoute: typeof AuthenticatedTrackBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVendorDashboardRoute: AuthenticatedVendorDashboardRoute,
  AuthenticatedCheckoutBookingIdRoute: AuthenticatedCheckoutBookingIdRoute,
  AuthenticatedExtendBookingIdRoute: AuthenticatedExtendBookingIdRoute,
  AuthenticatedTrackBookingIdRoute: AuthenticatedTrackBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BulkRentRoute: BulkRentRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  FleetRoute: FleetRoute,
  GalleryRoute: GalleryRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  RewardsRoute: RewardsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendorRegisterRoute: VendorRegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGalleryUploadRoute: ApiGalleryUploadRoute,
  BikeBikeIdRoute: BikeBikeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
