/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BulkRentRouteImport } from './routes/bulk-rent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BikeBikeIdRouteImport } from './routes/bike.$bikeId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedTrackBookingIdRouteImport } from './routes/_authenticated/track.$bookingId'
import { Route as AuthenticatedExtendBookingIdRouteImport } from './routes/_authenticated/extend.$bookingId'
import { Route as AuthenticatedCheckoutBookingIdRouteImport } from './routes/_authenticated/checkout.$bookingId'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRentRoute = BulkRentRouteImport.update({
  id: '/bulk-rent',
  path: '/bulk-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikeBikeIdRoute = BikeBikeIdRouteImport.update({
  id: '/bike/$bikeId',
  path: '/bike/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackBookingIdRoute =
  AuthenticatedTrackBookingIdRouteImport.update({
    id: '/track/$bookingId',
    path: '/track/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtendBookingIdRoute =
  AuthenticatedExtendBookingIdRouteImport.update({
    id: '/extend/$bookingId',
    path: '/extend/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutBookingIdRoute =
  AuthenticatedCheckoutBookingIdRouteImport.update({
    id: '/checkout/$bookingId',
    path: '/checkout/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk-rent': typeof BulkRentRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment-return': typeof PaymentReturnRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/bike/$bikeId': typeof BikeBikeIdRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/checkout/$bookingId': typeof AuthenticatedCheckoutBookingIdRoute
  '/extend/$bookingId': typeof AuthenticatedExtendBookingIdRoute
  '/track/$bookingId': typeof AuthenticatedTrackBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk-rent': typeof BulkRentRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment-return': typeof PaymentReturnRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/bike/$bikeId': typeof BikeBikeIdRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/checkout/$bookingId': typeof AuthenticatedCheckoutBookingIdRoute
  '/extend/$bookingId': typeof AuthenticatedExtendBookingIdRoute
  '/track/$bookingId': typeof AuthenticatedTrackBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bulk-rent': typeof BulkRentRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment-return': typeof PaymentReturnRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/bike/$bikeId': typeof BikeBikeIdRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/checkout/$bookingId': typeof AuthenticatedCheckoutBookingIdRoute
  '/_authenticated/extend/$bookingId': typeof AuthenticatedExtendBookingIdRoute
  '/_authenticated/track/$bookingId': typeof AuthenticatedTrackBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bulk-rent'
    | '/chat'
    | '/community'
    | '/fleet'
    | '/gallery'
    | '/onboarding'
    | '/otp'
    | '/payment-return'
    | '/rewards'
    | '/sitemap.xml'
    | '/verify-otp'
    | '/dashboard'
    | '/api/chat'
    | '/bike/$bikeId'
    | '/admin'
    | '/checkout/$bookingId'
    | '/extend/$bookingId'
    | '/track/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bulk-rent'
    | '/chat'
    | '/community'
    | '/fleet'
    | '/gallery'
    | '/onboarding'
    | '/otp'
    | '/payment-return'
    | '/rewards'
    | '/sitemap.xml'
    | '/verify-otp'
    | '/dashboard'
    | '/api/chat'
    | '/bike/$bikeId'
    | '/admin'
    | '/checkout/$bookingId'
    | '/extend/$bookingId'
    | '/track/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bulk-rent'
    | '/chat'
    | '/community'
    | '/fleet'
    | '/gallery'
    | '/onboarding'
    | '/otp'
    | '/payment-return'
    | '/rewards'
    | '/sitemap.xml'
    | '/verify-otp'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/bike/$bikeId'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/checkout/$bookingId'
    | '/_authenticated/extend/$bookingId'
    | '/_authenticated/track/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BulkRentRoute: typeof BulkRentRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  FleetRoute: typeof FleetRoute
  GalleryRoute: typeof GalleryRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  RewardsRoute: typeof RewardsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  ApiChatRoute: typeof ApiChatRoute
  BikeBikeIdRoute: typeof BikeBikeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-rent': {
      id: '/bulk-rent'
      path: '/bulk-rent'
      fullPath: '/bulk-rent'
      preLoaderRoute: typeof BulkRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike/$bikeId': {
      id: '/bike/$bikeId'
      path: '/bike/$bikeId'
      fullPath: '/bike/$bikeId'
      preLoaderRoute: typeof BikeBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/track/$bookingId': {
      id: '/_authenticated/track/$bookingId'
      path: '/track/$bookingId'
      fullPath: '/track/$bookingId'
      preLoaderRoute: typeof AuthenticatedTrackBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extend/$bookingId': {
      id: '/_authenticated/extend/$bookingId'
      path: '/extend/$bookingId'
      fullPath: '/extend/$bookingId'
      preLoaderRoute: typeof AuthenticatedExtendBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$bookingId': {
      id: '/_authenticated/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/checkout/$bookingId'
      preLoaderRoute: typeof AuthenticatedCheckoutBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCheckoutBookingIdRoute: typeof AuthenticatedCheckoutBookingIdRoute
  AuthenticatedExtendBookingIdRoute: typeof AuthenticatedExtendBookingIdRoute
  AuthenticatedTrackBookingIdRoute: typeof AuthenticatedTrackBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCheckoutBookingIdRoute: AuthenticatedCheckoutBookingIdRoute,
  AuthenticatedExtendBookingIdRoute: AuthenticatedExtendBookingIdRoute,
  AuthenticatedTrackBookingIdRoute: AuthenticatedTrackBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BulkRentRoute: BulkRentRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  FleetRoute: FleetRoute,
  GalleryRoute: GalleryRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  RewardsRoute: RewardsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  ApiChatRoute: ApiChatRoute,
  BikeBikeIdRoute: BikeBikeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
